log-level: info
importer:
  name: "algod"
  config:
    netaddr: "$ALGOD_ADDR"
    token: "$ALGOD_TOKEN"
    mode: "follower"
processors:
  - name: "filter_processor"
    config:
      filters:
        - any:
          - tag: "txn.type"
            expression-type: "equal"
            expression: "pay"
exporter:
  name: "postgresql"
  config:
    connection-string: $CONNECTION_STRING